# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_design = QtWidgets.QLabel(Form)
        self.label_design.setObjectName("label_design")
        self.verticalLayout_2.addWidget(self.label_design)
        self.all_designs_combo = QtWidgets.QComboBox(Form)
        self.all_designs_combo.setObjectName("all_designs_combo")
        self.verticalLayout_2.addWidget(self.all_designs_combo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ok_button = QtWidgets.QPushButton(Form)
        self.ok_button.setObjectName("ok_button")
        self.button_group = QtWidgets.QButtonGroup(Form)
        self.button_group.setObjectName("button_group")
        self.button_group.addButton(self.ok_button)
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(Form)
        self.cancel_button.setObjectName("cancel_button")
        self.button_group.addButton(self.cancel_button)
        self.horizontalLayout.addWidget(self.cancel_button)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_design.setText(_translate("Form", "Choose your design\n" +
                                             "To make changes, restart the program"))
        self.ok_button.setText(_translate("Form", "OK"))
        self.cancel_button.setText(_translate("Form", "Cancel"))
